version: '3.1'
services:
  mongodb:
    image: docker.io/library/mongo:5.0.9-focal
    restart: always
    ports:
      - "27017:27017"
    user: "${UID}:${GID}"
    volumes:
      - '~/appdata/mongodb:/data/db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    restart: always
    ports:
      - '8082:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/
    depends_on:
      - "mongodb"

  elasticsearch:
    image: elasticsearch:${STACK_VERSION}
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - "~/appdata/elasticsearch/data:/usr/share/elasticsearch/data"
    mem_limit: 734003200
    #ulimits:
      #memlock:
        #soft: -1
        #hard: -1
    environment:
      - node.name=es01
      - node.roles=[master, data]
      - cluster.name=${CLUSTER_NAME}
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=false

  kibana:
    image: kibana:${STACK_VERSION}
    volumes:
      - ~/appdata/kibana:/usr/share/kibana/data
    ports:
      - ${KIBANA_PORT}:5601
    mem_limit: 512000000
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:${STACK_VERSION}
    environment:
      - setup.kibana.host=kibana:5601
      - output.elasticsearch.hosts=["elasticsearch:9200"]
