version: '3.1'
services:
  mongodb:
    image: docker.io/library/mongo:5.0.9-focal
    restart: always
    ports:
      - 27017:27017
    #user: "${UID}:${GID}"
    #volumes:
      #- './mongodb:/data/db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/
    depends_on:
      - "mongodb"
