# trading service base config
server:
  port: 1000
  servlet:
    context-path: "/trading-bot"

spring:
  application:
    name: "trading-bot-service"
    title: "Trading Bot Service"
    version: 1.0
  profiles:
    active: "${ENV:dev}"
  banner:
    location: "classpath:banner.txt"
  data:
    mongodb:
      database: "tradedb"
      uri: "mongodb://localhost:27017"
  mvc:
    pathmatch:
      matching-strategy: "ant_path_matcher"

bux:
  server-api:
    token: "eyJhbGciOiJIUzI1NiJ9.eyJyZWZyZXNoYWJsZSI6ZmFsc2UsInN1YiI6ImJiMGNkYTJiLWExMGUtNGVkMy1hZDVhLTBmODJiNGMxNTJjNCIsImF1ZCI6ImJldGEuZ2V0YnV4LmNvbSIsInNjcCI6WyJhcHA6bG9naW4iLCJydGY6bG9naW4iXSwiZXhwIjoxODIwODQ5Mjc5LCJpYXQiOjE1MDU0ODkyNzksImp0aSI6ImI3MzlmYjgwLTM1NzUtNGIwMS04NzUxLTMzZDFhNGRjOGY5MiIsImNpZCI6Ijg0NzM2MjI5MzkifQ.M5oANIi2nBtSfIfhyUMqJnex-JYg6Sm92KPYaUL9GKg"
  trade:
    server: "https://api.beta.getbux.com"
  rtf-server: "ws://localhost:8080"

logging:
  level:
    bux:
      tradingbot: "INFO"
    org:
      springframework: "INFO"
      jeasy: "DEBUG"
    sanrocks:
      tradingbot: "INFO"
    reactor:
      netty: "INFO"
    graphql: "TRACE"

graphql:
  servlet:
    enabled: true
  #tools:
    #schemaLocationPattern: "**/*.graphqls"

eureka:
  client:
    serviceUrl:
      defaultZone: "${EUREKA_URI:http://localhost:8761/eureka}"
  instance:
    preferIpAddress: false

openapi:
  service:
    title: Trading Service
    version: 1.0.0
    url: http://localhost:8080 #api gateway url
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html